# Generated by Django 5.2 on 2025-04-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingupdate',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed'), ('Returned', 'Returned')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='trackingupdate',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
