# Generated by Django 5.2 on 2025-04-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_trackingupdate_options_trackingupdate_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
